### ISSUE TITLE
Support for aliases

### ISSUE THREAD

**Issue by jeremyvergnas** [zemirco/json2csv-stream#11]
We would like to provide labels/aliases for the headers.

In the documentation it says that we could manipulate the header 

```js
parser.on('header', function(data) {
  console.log(' ++ yeah header found ++');
  console.log(data);
});
```

So this is being called indeed, but when I return a comma separated string or an array of strings, it doesn't set it on the headers.

**Comment by knownasilya** [comment]
https://github.com/zemirco/json2csv now has a streams API, please use that module as this one is deprecated/unmaintained.
