### ISSUE TITLE
json2csv does not escape special / delimiter characters

### ISSUE THREAD

**Issue by mderazon** [zemirco/json2csv-stream#5]
according to csv spec,

>  "Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes."

http://stackoverflow.com/questions/769621/dealing-with-commas-in-a-csv-file

**Comment by kevbook** [comment]
Are you open to transferring the repo, so I can maintain it?

**Comment by knownasilya** [comment]
I'm here to accept PRs. I haven't done anything due to lack of interest from anyone. Once you have submitted a PR or two, we can add you as a collaborator.

**Comment by johnzhu12** [comment]
+1,same issue here

**Comment by knownasilya** [comment]
https://github.com/zemirco/json2csv now has a streams API, please use that module as this one is deprecated/unmaintained.
