### ISSUE TITLE
Parsing breaks when curly brace used inside text (regex)

### ISSUE THREAD

**Issue by g2010a** [zemirco/json2csv-stream#7]
The regular expression used to identify objects in the _transform function cannot cope with curly braces embedded in text. 

E.g. if the input file is
`[{"id":2089,"name":"[somename]{ep}: somethingelse","statusid":"o","something":false}]`

Then the following error will be raised:
`crit: uncaughtException SyntaxError: Unexpected end of input`

A possible fix is to use the following regular expression instead of what is being used now (index.js:77):

``` javascript
  // regular expression looking for json in chunk
  var re = /(?!\s|\}|$)\{[^\}"]*("(\\.|[^\\"])*"[^\}"]*)*\}/g;
```

**Comment by knownasilya** [comment]
@g2010a think you could submit a PR making the change?

**Comment by samuelwu90** [comment]
@knownasilya - looks like the fix has been merged.  Would you mind publishing a new version to npm with the fix? 😄

**Comment by montumodi** [comment]
@knownasilya Can you please publish the new version to npm with fix? We are facing a production issue because of this and need this urgently.

**Comment by knownasilya** [comment]
Published, thanks for the ping.
